[project]
name = "pyjinx"
version = "0.2.5"
description = "PyJinx - Python MVC framework"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Krunal Dodiya", email = "kunal.dodiya1@gmail.com" }]
license = "MIT"
dependencies = [
  "python-dotenv>=1.0.1",
  "pluralizer>=1.2.0",
  "colorama>=0.4.6",
  "jinja2>=3.1.4",
  "sqlalchemy>=2.0.52",
  "alembic>=1.19.0",
  "pendulum>=3.1.0",
]

[dependency-groups]
dev = [
  "cython>=3.0.11",
  "twine>=5.1.1",
  "wheel>=0.44.0",
  "mypy>=1.11.2",
  "pytest>=8.3.2",
]

[project.urls]
homepage = "https://www.proalgotrader.com"
repository = "https://github.com/pyjinx/framework"
documentation = "https://pyjinx.gitbook.io/docs"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["Illuminate*"]
